// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Share7.Infrastructure.Persistence;

#nullable disable

namespace Share7.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260810175831_GameCatalogAndProgress")]
    partial class GameCatalogAndProgress
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Share7.Domain.Curriculum.Chapter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId", "Order")
                        .IsUnique();

                    b.ToTable("Chapters", (string)null);
                });

            modelBuilder.Entity("Share7.Domain.Curriculum.ChapterTranslation", b =>
                {
                    b.Property<Guid>("ChapterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LangId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Lang_Id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ChapterId", "LangId");

                    b.HasIndex("LangId", "Name");

                    b.ToTable("ChapterTranslations", (string)null);
                });

            modelBuilder.Entity("Share7.Domain.Curriculum.Lesson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChapterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChapterId", "Order")
                        .IsUnique();

                    b.ToTable("Lessons", (string)null);
                });

            modelBuilder.Entity("Share7.Domain.Curriculum.LessonQuestionSet", b =>
                {
                    b.Property<Guid>("LessonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LangId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Lang_Id");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("LessonId", "LangId");

                    b.HasIndex("LangId");

                    b.ToTable("LessonQuestionSets", (string)null);
                });

            modelBuilder.Entity("Share7.Domain.Curriculum.LessonQuestionUpload", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<Guid>("LangId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Lang_Id");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("QuestionCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UploadedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LangId");

                    b.HasIndex("LessonId", "LangId", "Version")
                        .IsUnique();

                    b.ToTable("LessonQuestionUploads", (string)null);
                });

            modelBuilder.Entity("Share7.Domain.Curriculum.LessonTranslation", b =>
                {
                    b.Property<Guid>("LessonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LangId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Lang_Id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("LessonId", "LangId");

                    b.HasIndex("LangId", "Name");

                    b.ToTable("LessonTranslations", (string)null);
                });

            modelBuilder.Entity("Share7.Domain.Curriculum.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CorrectChoiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeactivatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<Guid>("LangId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Lang_Id");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RowNumber")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("Question");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LangId");

                    b.HasIndex("LessonId", "LangId", "IsActive");

                    b.ToTable("Questions", (string)null);
                });

            modelBuilder.Entity("Share7.Domain.Curriculum.QuestionChoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Choice");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("QuestionChoices", (string)null);
                });

            modelBuilder.Entity("Share7.Domain.Curriculum.Subject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<Guid>("TermId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TermId", "Order")
                        .IsUnique();

                    b.ToTable("Subjects", (string)null);
                });

            modelBuilder.Entity("Share7.Domain.Curriculum.SubjectTranslation", b =>
                {
                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LangId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Lang_Id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("SubjectId", "LangId");

                    b.HasIndex("LangId", "Name");

                    b.ToTable("SubjectTranslations", (string)null);
                });

            modelBuilder.Entity("Share7.Domain.Curriculum.Term", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GradeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GradeId", "Order")
                        .IsUnique();

                    b.ToTable("Terms", (string)null);
                });

            modelBuilder.Entity("Share7.Domain.Curriculum.TermTranslation", b =>
                {
                    b.Property<Guid>("TermId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LangId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Lang_Id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TermId", "LangId");

                    b.HasIndex("LangId", "Name");

                    b.ToTable("TermTranslations", (string)null);
                });

            modelBuilder.Entity("Share7.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReasonRevoked")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReplacedByToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RevokedByIp")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("Share7.Domain.Entities.StudentProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("GradeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("GradeId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("StudentProfiles", (string)null);
                });

            modelBuilder.Entity("Share7.Domain.Games.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GameKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("GameplayScene")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("LobbyScene")
                        .HasColumnType("int");

                    b.Property<int>("MaxPlayers")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(2);

                    b.Property<int>("MinPlayers")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<float>("ReadyTimeoutSeconds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("real")
                        .HasDefaultValue(20f);

                    b.Property<bool>("SupportsMultiplayer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("SupportsSinglePlayer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("UseLobby")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("UseMatchmaking")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("Id");

                    b.HasIndex("GameKey")
                        .IsUnique();

                    b.ToTable("Games", (string)null);
                });

            modelBuilder.Entity("Share7.Domain.Games.GameTranslation", b =>
                {
                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LangId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Lang_Id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("GameId", "LangId");

                    b.HasIndex("LangId");

                    b.ToTable("GameTranslations", (string)null);
                });

            modelBuilder.Entity("Share7.Domain.LookUps.Grade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Order")
                        .IsUnique();

                    b.ToTable("Grades", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a0000000-0000-4000-8000-000000000001"),
                            Order = 1
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-4000-8000-000000000002"),
                            Order = 2
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-4000-8000-000000000003"),
                            Order = 3
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-4000-8000-000000000004"),
                            Order = 4
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-4000-8000-000000000005"),
                            Order = 5
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-4000-8000-000000000006"),
                            Order = 6
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-4000-8000-000000000007"),
                            Order = 7
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-4000-8000-000000000008"),
                            Order = 8
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-4000-8000-000000000009"),
                            Order = 9
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-4000-8000-00000000000a"),
                            Order = 10
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-4000-8000-00000000000b"),
                            Order = 11
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-4000-8000-00000000000c"),
                            Order = 12
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-4000-8000-00000000000d"),
                            Order = 13
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-4000-8000-00000000000e"),
                            Order = 14
                        });
                });

            modelBuilder.Entity("Share7.Domain.LookUps.GradeTranslation", b =>
                {
                    b.Property<Guid>("GradeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LangId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Lang_Id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("GradeId", "LangId");

                    b.HasIndex("LangId", "Name");

                    b.ToTable("GradeTranslations", (string)null);

                    b.HasData(
                        new
                        {
                            GradeId = new Guid("a0000000-0000-4000-8000-000000000001"),
                            LangId = new Guid("9c4d7f2a-3e51-4b6c-8d0a-2f7b1e5c9a34"),
                            Name = "KG1"
                        },
                        new
                        {
                            GradeId = new Guid("a0000000-0000-4000-8000-000000000001"),
                            LangId = new Guid("4b8e1d6f-7a29-4c35-9e10-6d3f8b2a5c71"),
                            Name = "الروضة الأولى"
                        },
                        new
                        {
                            GradeId = new Guid("a0000000-0000-4000-8000-000000000002"),
                            LangId = new Guid("9c4d7f2a-3e51-4b6c-8d0a-2f7b1e5c9a34"),
                            Name = "KG2"
                        },
                        new
                        {
                            GradeId = new Guid("a0000000-0000-4000-8000-000000000002"),
                            LangId = new Guid("4b8e1d6f-7a29-4c35-9e10-6d3f8b2a5c71"),
                            Name = "الروضة الثانية"
                        },
                        new
                        {
                            GradeId = new Guid("a0000000-0000-4000-8000-000000000003"),
                            LangId = new Guid("9c4d7f2a-3e51-4b6c-8d0a-2f7b1e5c9a34"),
                            Name = "Primary One"
                        },
                        new
                        {
                            GradeId = new Guid("a0000000-0000-4000-8000-000000000003"),
                            LangId = new Guid("4b8e1d6f-7a29-4c35-9e10-6d3f8b2a5c71"),
                            Name = "الصف الأول الابتدائي"
                        },
                        new
                        {
                            GradeId = new Guid("a0000000-0000-4000-8000-000000000004"),
                            LangId = new Guid("9c4d7f2a-3e51-4b6c-8d0a-2f7b1e5c9a34"),
                            Name = "Primary Two"
                        },
                        new
                        {
                            GradeId = new Guid("a0000000-0000-4000-8000-000000000004"),
                            LangId = new Guid("4b8e1d6f-7a29-4c35-9e10-6d3f8b2a5c71"),
                            Name = "الصف الثاني الابتدائي"
                        },
                        new
                        {
                            GradeId = new Guid("a0000000-0000-4000-8000-000000000005"),
                            LangId = new Guid("9c4d7f2a-3e51-4b6c-8d0a-2f7b1e5c9a34"),
                            Name = "Primary Three"
                        },
                        new
                        {
                            GradeId = new Guid("a0000000-0000-4000-8000-000000000005"),
                            LangId = new Guid("4b8e1d6f-7a29-4c35-9e10-6d3f8b2a5c71"),
                            Name = "الصف الثالث الابتدائي"
                        },
                        new
                        {
                            GradeId = new Guid("a0000000-0000-4000-8000-000000000006"),
                            LangId = new Guid("9c4d7f2a-3e51-4b6c-8d0a-2f7b1e5c9a34"),
                            Name = "Primary Four"
                        },
                        new
                        {
                            GradeId = new Guid("a0000000-0000-4000-8000-000000000006"),
                            LangId = new Guid("4b8e1d6f-7a29-4c35-9e10-6d3f8b2a5c71"),
                            Name = "الصف الرابع الابتدائي"
                        },
                        new
                        {
                            GradeId = new Guid("a0000000-0000-4000-8000-000000000007"),
                            LangId = new Guid("9c4d7f2a-3e51-4b6c-8d0a-2f7b1e5c9a34"),
                            Name = "Primary Five"
                        },
                        new
                        {
                            GradeId = new Guid("a0000000-0000-4000-8000-000000000007"),
                            LangId = new Guid("4b8e1d6f-7a29-4c35-9e10-6d3f8b2a5c71"),
                            Name = "الصف الخامس الابتدائي"
                        },
                        new
                        {
                            GradeId = new Guid("a0000000-0000-4000-8000-000000000008"),
                            LangId = new Guid("9c4d7f2a-3e51-4b6c-8d0a-2f7b1e5c9a34"),
                            Name = "Primary Six"
                        },
                        new
                        {
                            GradeId = new Guid("a0000000-0000-4000-8000-000000000008"),
                            LangId = new Guid("4b8e1d6f-7a29-4c35-9e10-6d3f8b2a5c71"),
                            Name = "الصف السادس الابتدائي"
                        },
                        new
                        {
                            GradeId = new Guid("a0000000-0000-4000-8000-000000000009"),
                            LangId = new Guid("9c4d7f2a-3e51-4b6c-8d0a-2f7b1e5c9a34"),
                            Name = "Preparatory One"
                        },
                        new
                        {
                            GradeId = new Guid("a0000000-0000-4000-8000-000000000009"),
                            LangId = new Guid("4b8e1d6f-7a29-4c35-9e10-6d3f8b2a5c71"),
                            Name = "الصف الأول الإعدادي"
                        },
                        new
                        {
                            GradeId = new Guid("a0000000-0000-4000-8000-00000000000a"),
                            LangId = new Guid("9c4d7f2a-3e51-4b6c-8d0a-2f7b1e5c9a34"),
                            Name = "Preparatory Two"
                        },
                        new
                        {
                            GradeId = new Guid("a0000000-0000-4000-8000-00000000000a"),
                            LangId = new Guid("4b8e1d6f-7a29-4c35-9e10-6d3f8b2a5c71"),
                            Name = "الصف الثاني الإعدادي"
                        },
                        new
                        {
                            GradeId = new Guid("a0000000-0000-4000-8000-00000000000b"),
                            LangId = new Guid("9c4d7f2a-3e51-4b6c-8d0a-2f7b1e5c9a34"),
                            Name = "Preparatory Three"
                        },
                        new
                        {
                            GradeId = new Guid("a0000000-0000-4000-8000-00000000000b"),
                            LangId = new Guid("4b8e1d6f-7a29-4c35-9e10-6d3f8b2a5c71"),
                            Name = "الصف الثالث الإعدادي"
                        },
                        new
                        {
                            GradeId = new Guid("a0000000-0000-4000-8000-00000000000c"),
                            LangId = new Guid("9c4d7f2a-3e51-4b6c-8d0a-2f7b1e5c9a34"),
                            Name = "Secondary One"
                        },
                        new
                        {
                            GradeId = new Guid("a0000000-0000-4000-8000-00000000000c"),
                            LangId = new Guid("4b8e1d6f-7a29-4c35-9e10-6d3f8b2a5c71"),
                            Name = "الصف الأول الثانوي"
                        },
                        new
                        {
                            GradeId = new Guid("a0000000-0000-4000-8000-00000000000d"),
                            LangId = new Guid("9c4d7f2a-3e51-4b6c-8d0a-2f7b1e5c9a34"),
                            Name = "Secondary Two"
                        },
                        new
                        {
                            GradeId = new Guid("a0000000-0000-4000-8000-00000000000d"),
                            LangId = new Guid("4b8e1d6f-7a29-4c35-9e10-6d3f8b2a5c71"),
                            Name = "الصف الثاني الثانوي"
                        },
                        new
                        {
                            GradeId = new Guid("a0000000-0000-4000-8000-00000000000e"),
                            LangId = new Guid("9c4d7f2a-3e51-4b6c-8d0a-2f7b1e5c9a34"),
                            Name = "Secondary Three"
                        },
                        new
                        {
                            GradeId = new Guid("a0000000-0000-4000-8000-00000000000e"),
                            LangId = new Guid("4b8e1d6f-7a29-4c35-9e10-6d3f8b2a5c71"),
                            Name = "الصف الثالث الثانوي"
                        });
                });

            modelBuilder.Entity("Share7.Domain.LookUps.Language", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Languages", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("9c4d7f2a-3e51-4b6c-8d0a-2f7b1e5c9a34"),
                            Code = "en",
                            Name = "English"
                        },
                        new
                        {
                            Id = new Guid("4b8e1d6f-7a29-4c35-9e10-6d3f8b2a5c71"),
                            Code = "ar",
                            Name = "العربية"
                        });
                });

            modelBuilder.Entity("Share7.Domain.Progress.UserLessonProgress", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Attempts")
                        .HasColumnType("int");

                    b.Property<int>("CompletionState")
                        .HasColumnType("int");

                    b.Property<int>("CorrectCount")
                        .HasColumnType("int");

                    b.Property<bool>("FirstAttemptWasPerfect")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastAttemptAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Percent")
                        .HasColumnType("int");

                    b.Property<int>("QuestionsVersion")
                        .HasColumnType("int");

                    b.Property<int>("TotalCount")
                        .HasColumnType("int");

                    b.HasKey("UserId", "GameId", "LessonId");

                    b.HasIndex("GameId");

                    b.HasIndex("LessonId");

                    b.HasIndex("UserId", "GameId");

                    b.ToTable("UserLessonProgress", (string)null);
                });

            modelBuilder.Entity("Share7.Domain.Progress.UserNodeUnlock", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("NodeType")
                        .HasColumnType("int");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UnlockedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId", "GameId", "NodeType", "NodeId");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId", "GameId");

                    b.ToTable("UserNodeUnlocks", (string)null);
                });

            modelBuilder.Entity("Share7.Domain.Progress.UserQuestionProgress", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Attempts")
                        .HasColumnType("int");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastAttemptAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "GameId", "QuestionId");

                    b.HasIndex("GameId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("UserId", "GameId", "LessonId");

                    b.ToTable("UserQuestionProgress", (string)null);
                });

            modelBuilder.Entity("Share7.Infrastructure.Identity.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Share7.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<Guid?>("PreferredLanguageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Share7.Infrastructure.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Share7.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Share7.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Share7.Infrastructure.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Share7.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Share7.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Share7.Domain.Curriculum.Chapter", b =>
                {
                    b.HasOne("Share7.Domain.Curriculum.Subject", "Subject")
                        .WithMany("Chapters")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("Share7.Domain.Curriculum.ChapterTranslation", b =>
                {
                    b.HasOne("Share7.Domain.Curriculum.Chapter", "Chapter")
                        .WithMany("Translations")
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Share7.Domain.LookUps.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LangId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Chapter");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("Share7.Domain.Curriculum.Lesson", b =>
                {
                    b.HasOne("Share7.Domain.Curriculum.Chapter", "Chapter")
                        .WithMany("Lessons")
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chapter");
                });

            modelBuilder.Entity("Share7.Domain.Curriculum.LessonQuestionSet", b =>
                {
                    b.HasOne("Share7.Domain.LookUps.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LangId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Share7.Domain.Curriculum.Lesson", "Lesson")
                        .WithMany("QuestionSets")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("Share7.Domain.Curriculum.LessonQuestionUpload", b =>
                {
                    b.HasOne("Share7.Domain.LookUps.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LangId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Share7.Domain.Curriculum.Lesson", "Lesson")
                        .WithMany()
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("Share7.Domain.Curriculum.LessonTranslation", b =>
                {
                    b.HasOne("Share7.Domain.LookUps.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LangId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Share7.Domain.Curriculum.Lesson", "Lesson")
                        .WithMany("Translations")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("Share7.Domain.Curriculum.Question", b =>
                {
                    b.HasOne("Share7.Domain.LookUps.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LangId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Share7.Domain.Curriculum.Lesson", "Lesson")
                        .WithMany("Questions")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("Share7.Domain.Curriculum.QuestionChoice", b =>
                {
                    b.HasOne("Share7.Domain.Curriculum.Question", "Question")
                        .WithMany("Choices")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Share7.Domain.Curriculum.Subject", b =>
                {
                    b.HasOne("Share7.Domain.Curriculum.Term", "Term")
                        .WithMany("Subjects")
                        .HasForeignKey("TermId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Term");
                });

            modelBuilder.Entity("Share7.Domain.Curriculum.SubjectTranslation", b =>
                {
                    b.HasOne("Share7.Domain.LookUps.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LangId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Share7.Domain.Curriculum.Subject", "Subject")
                        .WithMany("Translations")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("Share7.Domain.Curriculum.Term", b =>
                {
                    b.HasOne("Share7.Domain.LookUps.Grade", "Grade")
                        .WithMany("Terms")
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grade");
                });

            modelBuilder.Entity("Share7.Domain.Curriculum.TermTranslation", b =>
                {
                    b.HasOne("Share7.Domain.LookUps.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LangId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Share7.Domain.Curriculum.Term", "Term")
                        .WithMany("Translations")
                        .HasForeignKey("TermId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Term");
                });

            modelBuilder.Entity("Share7.Domain.Entities.StudentProfile", b =>
                {
                    b.HasOne("Share7.Domain.LookUps.Grade", "Grade")
                        .WithMany()
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Grade");
                });

            modelBuilder.Entity("Share7.Domain.Games.GameTranslation", b =>
                {
                    b.HasOne("Share7.Domain.Games.Game", "Game")
                        .WithMany("Translations")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Share7.Domain.LookUps.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LangId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("Share7.Domain.LookUps.GradeTranslation", b =>
                {
                    b.HasOne("Share7.Domain.LookUps.Grade", "Grade")
                        .WithMany("Translations")
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Share7.Domain.LookUps.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LangId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Grade");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("Share7.Domain.Progress.UserLessonProgress", b =>
                {
                    b.HasOne("Share7.Domain.Games.Game", null)
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Share7.Domain.Curriculum.Lesson", null)
                        .WithMany()
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Share7.Domain.Progress.UserNodeUnlock", b =>
                {
                    b.HasOne("Share7.Domain.Games.Game", null)
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Share7.Domain.Progress.UserQuestionProgress", b =>
                {
                    b.HasOne("Share7.Domain.Games.Game", null)
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Share7.Domain.Curriculum.Question", null)
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Share7.Domain.Curriculum.Chapter", b =>
                {
                    b.Navigation("Lessons");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Share7.Domain.Curriculum.Lesson", b =>
                {
                    b.Navigation("QuestionSets");

                    b.Navigation("Questions");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Share7.Domain.Curriculum.Question", b =>
                {
                    b.Navigation("Choices");
                });

            modelBuilder.Entity("Share7.Domain.Curriculum.Subject", b =>
                {
                    b.Navigation("Chapters");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Share7.Domain.Curriculum.Term", b =>
                {
                    b.Navigation("Subjects");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Share7.Domain.Games.Game", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Share7.Domain.LookUps.Grade", b =>
                {
                    b.Navigation("Terms");

                    b.Navigation("Translations");
                });
#pragma warning restore 612, 618
        }
    }
}
