// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Share7.Infrastructure.Persistence;

#nullable disable

namespace Share7.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Share7.Domain.Curriculum.Chapter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LangId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Lang_Id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Chapter");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LangId");

                    b.HasIndex("SubjectId");

                    b.ToTable("Chapters", (string)null);
                });

            modelBuilder.Entity("Share7.Domain.Curriculum.Lesson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChapterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LangId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Lang_Id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Lesson");

                    b.Property<int>("QuestionsVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("ChapterId");

                    b.HasIndex("LangId");

                    b.ToTable("Lessons", (string)null);
                });

            modelBuilder.Entity("Share7.Domain.Curriculum.LessonQuestionUpload", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("QuestionCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UploadedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LessonId", "Version")
                        .IsUnique();

                    b.ToTable("LessonQuestionUploads", (string)null);
                });

            modelBuilder.Entity("Share7.Domain.Curriculum.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CorrectChoiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeactivatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<Guid>("LangId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Lang_Id");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RowNumber")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("Question");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LangId");

                    b.HasIndex("LessonId", "IsActive");

                    b.ToTable("Questions", (string)null);
                });

            modelBuilder.Entity("Share7.Domain.Curriculum.QuestionChoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Choice");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("QuestionChoices", (string)null);
                });

            modelBuilder.Entity("Share7.Domain.Curriculum.Subject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LangId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Lang_Id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Subject");

                    b.Property<Guid>("TermId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LangId");

                    b.HasIndex("TermId");

                    b.ToTable("Subjects", (string)null);
                });

            modelBuilder.Entity("Share7.Domain.Curriculum.Term", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GradeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LangId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Lang_Id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Term");

                    b.HasKey("Id");

                    b.HasIndex("GradeId");

                    b.HasIndex("LangId");

                    b.ToTable("Terms", (string)null);
                });

            modelBuilder.Entity("Share7.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReasonRevoked")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReplacedByToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RevokedByIp")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("Share7.Domain.Entities.StudentProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("GradeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("GradeId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("StudentProfiles", (string)null);
                });

            modelBuilder.Entity("Share7.Domain.LookUps.Grade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LangId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Lang_Id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Grade");

                    b.HasKey("Id");

                    b.HasIndex("LangId");

                    b.ToTable("Grades", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("ee0bc8b5-de4a-4a25-afaa-cfdec9e9e27a"),
                            LangId = new Guid("9c4d7f2a-3e51-4b6c-8d0a-2f7b1e5c9a34"),
                            Name = "Grade 1"
                        },
                        new
                        {
                            Id = new Guid("cc203a51-cc8c-4814-ae5e-587c9903e17c"),
                            LangId = new Guid("9c4d7f2a-3e51-4b6c-8d0a-2f7b1e5c9a34"),
                            Name = "Grade 2"
                        },
                        new
                        {
                            Id = new Guid("52c97299-9356-46d5-87e9-fc1ac17d5c14"),
                            LangId = new Guid("9c4d7f2a-3e51-4b6c-8d0a-2f7b1e5c9a34"),
                            Name = "Grade 3"
                        },
                        new
                        {
                            Id = new Guid("2b004d42-ca9c-4823-ac5b-1cb59cba0467"),
                            LangId = new Guid("9c4d7f2a-3e51-4b6c-8d0a-2f7b1e5c9a34"),
                            Name = "Grade 4"
                        },
                        new
                        {
                            Id = new Guid("b14d62e5-56ee-42a4-916a-5554d811f72f"),
                            LangId = new Guid("9c4d7f2a-3e51-4b6c-8d0a-2f7b1e5c9a34"),
                            Name = "Grade 5"
                        },
                        new
                        {
                            Id = new Guid("76e10c16-da74-4731-8818-448262946b70"),
                            LangId = new Guid("9c4d7f2a-3e51-4b6c-8d0a-2f7b1e5c9a34"),
                            Name = "Grade 6"
                        },
                        new
                        {
                            Id = new Guid("c3f4e414-cde4-4929-a235-d4f09b5f748d"),
                            LangId = new Guid("9c4d7f2a-3e51-4b6c-8d0a-2f7b1e5c9a34"),
                            Name = "Grade 7"
                        },
                        new
                        {
                            Id = new Guid("de6e690a-9bbf-4e32-afea-7e36942f7957"),
                            LangId = new Guid("9c4d7f2a-3e51-4b6c-8d0a-2f7b1e5c9a34"),
                            Name = "Grade 8"
                        },
                        new
                        {
                            Id = new Guid("895f300d-21b4-4167-afc7-6c06677abf0e"),
                            LangId = new Guid("9c4d7f2a-3e51-4b6c-8d0a-2f7b1e5c9a34"),
                            Name = "Grade 9"
                        },
                        new
                        {
                            Id = new Guid("f4313c32-260c-4e55-8877-c68b9d5ae33d"),
                            LangId = new Guid("9c4d7f2a-3e51-4b6c-8d0a-2f7b1e5c9a34"),
                            Name = "Grade 10"
                        },
                        new
                        {
                            Id = new Guid("c2287d7b-e111-45ef-ac10-a3669c8a5eeb"),
                            LangId = new Guid("9c4d7f2a-3e51-4b6c-8d0a-2f7b1e5c9a34"),
                            Name = "Grade 11"
                        },
                        new
                        {
                            Id = new Guid("38111b66-de42-4adc-b20c-464b1dd2a9d1"),
                            LangId = new Guid("9c4d7f2a-3e51-4b6c-8d0a-2f7b1e5c9a34"),
                            Name = "Grade 12"
                        },
                        new
                        {
                            Id = new Guid("a1e6c390-7d24-4f81-9b05-3c8e2a6f4d17"),
                            LangId = new Guid("4b8e1d6f-7a29-4c35-9e10-6d3f8b2a5c71"),
                            Name = "الصف الأول"
                        },
                        new
                        {
                            Id = new Guid("b2f7d4a1-8e35-4092-ac16-4d9f3b7e5a28"),
                            LangId = new Guid("4b8e1d6f-7a29-4c35-9e10-6d3f8b2a5c71"),
                            Name = "الصف الثاني"
                        },
                        new
                        {
                            Id = new Guid("c3a8e5b2-9f46-41a3-bd27-5e0a4c8f6b39"),
                            LangId = new Guid("4b8e1d6f-7a29-4c35-9e10-6d3f8b2a5c71"),
                            Name = "الصف الثالث"
                        },
                        new
                        {
                            Id = new Guid("d4b9f6c3-a057-42b4-ce38-6f1b5d907c4a"),
                            LangId = new Guid("4b8e1d6f-7a29-4c35-9e10-6d3f8b2a5c71"),
                            Name = "الصف الرابع"
                        },
                        new
                        {
                            Id = new Guid("e5c0a7d4-b168-43c5-df49-701c6e018d5b"),
                            LangId = new Guid("4b8e1d6f-7a29-4c35-9e10-6d3f8b2a5c71"),
                            Name = "الصف الخامس"
                        },
                        new
                        {
                            Id = new Guid("f6d1b8e5-c279-44d6-e05a-812d7f129e6c"),
                            LangId = new Guid("4b8e1d6f-7a29-4c35-9e10-6d3f8b2a5c71"),
                            Name = "الصف السادس"
                        },
                        new
                        {
                            Id = new Guid("07e2c9f6-d38a-45e7-f16b-923e80230f7d"),
                            LangId = new Guid("4b8e1d6f-7a29-4c35-9e10-6d3f8b2a5c71"),
                            Name = "الصف السابع"
                        },
                        new
                        {
                            Id = new Guid("18f3d007-e49b-46f8-021c-a34f9134108e"),
                            LangId = new Guid("4b8e1d6f-7a29-4c35-9e10-6d3f8b2a5c71"),
                            Name = "الصف الثامن"
                        },
                        new
                        {
                            Id = new Guid("2904e118-f5ac-4709-132d-b450a245219f"),
                            LangId = new Guid("4b8e1d6f-7a29-4c35-9e10-6d3f8b2a5c71"),
                            Name = "الصف التاسع"
                        },
                        new
                        {
                            Id = new Guid("3a15f229-06bd-481a-243e-c561b35632a0"),
                            LangId = new Guid("4b8e1d6f-7a29-4c35-9e10-6d3f8b2a5c71"),
                            Name = "الصف العاشر"
                        },
                        new
                        {
                            Id = new Guid("4b260330-17ce-492b-354f-d672c46743b1"),
                            LangId = new Guid("4b8e1d6f-7a29-4c35-9e10-6d3f8b2a5c71"),
                            Name = "الصف الحادي عشر"
                        },
                        new
                        {
                            Id = new Guid("5c371441-28df-4a3c-4650-e783d57854c2"),
                            LangId = new Guid("4b8e1d6f-7a29-4c35-9e10-6d3f8b2a5c71"),
                            Name = "الصف الثاني عشر"
                        });
                });

            modelBuilder.Entity("Share7.Domain.LookUps.Language", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Languages", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("9c4d7f2a-3e51-4b6c-8d0a-2f7b1e5c9a34"),
                            Code = "en",
                            Name = "English"
                        },
                        new
                        {
                            Id = new Guid("4b8e1d6f-7a29-4c35-9e10-6d3f8b2a5c71"),
                            Code = "ar",
                            Name = "العربية"
                        });
                });

            modelBuilder.Entity("Share7.Infrastructure.Identity.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Share7.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<Guid?>("PreferredLanguageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Share7.Infrastructure.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Share7.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Share7.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Share7.Infrastructure.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Share7.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Share7.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Share7.Domain.Curriculum.Chapter", b =>
                {
                    b.HasOne("Share7.Domain.LookUps.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LangId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Share7.Domain.Curriculum.Subject", "Subject")
                        .WithMany("Chapters")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("Share7.Domain.Curriculum.Lesson", b =>
                {
                    b.HasOne("Share7.Domain.Curriculum.Chapter", "Chapter")
                        .WithMany("Lessons")
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Share7.Domain.LookUps.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LangId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Chapter");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("Share7.Domain.Curriculum.LessonQuestionUpload", b =>
                {
                    b.HasOne("Share7.Domain.Curriculum.Lesson", "Lesson")
                        .WithMany()
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("Share7.Domain.Curriculum.Question", b =>
                {
                    b.HasOne("Share7.Domain.LookUps.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LangId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Share7.Domain.Curriculum.Lesson", "Lesson")
                        .WithMany("Questions")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("Share7.Domain.Curriculum.QuestionChoice", b =>
                {
                    b.HasOne("Share7.Domain.Curriculum.Question", "Question")
                        .WithMany("Choices")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Share7.Domain.Curriculum.Subject", b =>
                {
                    b.HasOne("Share7.Domain.LookUps.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LangId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Share7.Domain.Curriculum.Term", "Term")
                        .WithMany("Subjects")
                        .HasForeignKey("TermId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Term");
                });

            modelBuilder.Entity("Share7.Domain.Curriculum.Term", b =>
                {
                    b.HasOne("Share7.Domain.LookUps.Grade", "Grade")
                        .WithMany("Terms")
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Share7.Domain.LookUps.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LangId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Grade");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("Share7.Domain.Entities.StudentProfile", b =>
                {
                    b.HasOne("Share7.Domain.LookUps.Grade", "Grade")
                        .WithMany()
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Grade");
                });

            modelBuilder.Entity("Share7.Domain.LookUps.Grade", b =>
                {
                    b.HasOne("Share7.Domain.LookUps.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LangId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Language");
                });

            modelBuilder.Entity("Share7.Domain.Curriculum.Chapter", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("Share7.Domain.Curriculum.Lesson", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("Share7.Domain.Curriculum.Question", b =>
                {
                    b.Navigation("Choices");
                });

            modelBuilder.Entity("Share7.Domain.Curriculum.Subject", b =>
                {
                    b.Navigation("Chapters");
                });

            modelBuilder.Entity("Share7.Domain.Curriculum.Term", b =>
                {
                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("Share7.Domain.LookUps.Grade", b =>
                {
                    b.Navigation("Terms");
                });
#pragma warning restore 612, 618
        }
    }
}
